server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/workout_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none  # Временно отключаем валидацию, чтобы Liquibase создал таблицы
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/workout-realm

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yaml
    contexts: ${LIQUIBASE_CONTEXTS:}
    default-schema: public

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.workout.controller

logging:
  level:
    root: INFO
    com.workout: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
