apiVersion: v2
name: postgresql
description: PostgreSQL database for workout backend
type: application
version: 0.1.0
appVersion: "15.0"
keywords:
  - postgresql
  - database
  - sql
home: https://www.postgresql.org/
sources:
  - https://github.com/postgres/postgres
maintainers:
  - name: Your Name
    email: your.email@example.com
