apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.env.KEYCLOAK_ADMIN }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.env.KEYCLOAK_ADMIN_PASSWORD }}
            - name: KC_DB
              value: {{ .Values.env.KC_DB }}
            - name: KC_DB_URL
              value: {{ .Values.env.KC_DB_URL }}
            - name: KC_DB_USERNAME
              value: {{ .Values.env.KC_DB_USERNAME }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.env.KC_DB_PASSWORD }}
          command:
            - /opt/keycloak/bin/kc.sh
            - start
            - --optimized
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/keycloak/data
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "keycloak.fullname" . }}-pvc
      {{- end }}
