apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workout-app.fullname" . }}-config
  labels:
    {{- include "workout-app.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      profiles:
        active: kubernetes
      
      datasource:
        url: jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
        username: {{ .Values.database.username }}
        password: {{ .Values.database.password }}
        driver-class-name: org.postgresql.Driver
      
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: false
      
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.security.jwt.issuer }}
              audience: {{ .Values.security.jwt.audience }}
      
      servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
    
    server:
      port: {{ .Values.service.targetPort }}
      servlet:
        context-path: /
    
    logging:
      level:
        com.workout: DEBUG
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
    
    minio:
      endpoint: http://{{ include "workout-app.fullname" . }}-minio:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket: workout-media
