spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/workout_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/workout-realm}

logging:
  level:
    root: INFO
    com.workout: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
