server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/workout_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # В debug профиле ОТКЛЮЧАЕМ JWT аутентификацию
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/workout-realm}

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.workout.controller

logging:
  level:
    root: INFO
    com.workout: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# MinIO Configuration
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:workout-media}
