# Default values for workout-backend
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: jfrog.topilins.com:443/docker/health-improve-workout-backend
  tag: "v6"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: jfroglocal
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8082

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Database configuration
database:
  enabled: true
  type: postgresql
  host: helth-postgres-postgresql
  port: 5432
  name: workout_db
  username: postgres
  password: postgres
  existingSecret: ""

# MinIO configuration
minio:
  enabled: true
  host: minio
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: workout-media
  existingSecret: ""

# Keycloak configuration
keycloak:
  enabled: true
  host: 192.168.234.114
  port: 31036
  realm: workout-realm
  clientId: workout-client
  existingSecret: ""

# Application specific configuration
app:
  server:
    port: 8082
  logging:
    level: INFO
  profiles:
    active: prod
  cors:
    allowedOrigins: "*"
    allowedMethods: "*"
    allowedHeaders: "*"
